server:
  port: 8081
spring:
  application.name: bookstore-management-system
  profiles.active: local
  datasource:
    url: jdbc:mysql://localhost:3306/bookdb?useSSL=false
    username: root
    password: abhijit@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 30000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true